### ISSUE TITLE
USB device connections?

### ISSUE THREAD

**Issue by nettlep** [ShawnHymel/rpi-cm4-base-carrier#2]
I'd like to support plugging in a USB microphone.

Can I use the Micro-USB connector for this? I'm hoping that I can use this connector for a dual purpose. Uploading the OS (with the nRPIBOOT jumper closed) or as a USB port (with the jumper open).

Is this possible or would I need to include a USB host controller like the one in the reference CM4IO board?

**Comment by ShawnHymel** [comment]
Hi @nettlep,

That USB port should be an OTG port that you can switch between host and device mode. The IO board has a MUX that allows you to switch between host and client on two different connectors. See this thread for more info: https://forums.raspberrypi.com/viewtopic.php?t=290260
